name: SpongeBox
main: me.darknessdecends.spongebox.SpongeBox
version: 1.2
website: http://www.polygoncraft.net
description: Teleports a player to a SpongeBox at a specified location
author: DarknessDecends
commands: 
    sponge:
        description: Teleports A player to the SpongeBox
        usage: §cThe correct format is /sponge [player_name]
        permission: spongebox.sponge
    spongeboxreload:
        description: Reloads SpongeBox
        usage: §cThe correct format is /spongeboxreload
        permission: spongebox.reload

